let t = document.body.firstElementChild.firstElementChild;
console.log(t.caption);
console.log(t.rows);
console.log(t.tHead);
console.log(t.tFoot);
console.log(t.tBodies);
console.log(t.rows);
console.log(t.rows.length);
console.log(t.rows[0].rowIndex);
console.log(t.rows[1].cellIndex);
